/*******************************************************************************
* KindEditor - WYSIWYG HTML Editor for Internet
* Copyright (C) 2006-2011 kindsoft.net
*
* @author Roddy <luolonghao@gmail.com>
* @site http://www.kindsoft.net/
* @licence http://www.kindsoft.net/license.php
*******************************************************************************/

KindEditor.lang({
	source : 'HTML代碼',
	preview : '預覽',
	undo : '復原(Ctrl+Z)',
	redo : '前進(Ctrl+Y)',
	cut : '剪下(Ctrl+X)',
	copy : '複製(Ctrl+C)',
	paste : '貼上(Ctrl+V)',
	plainpaste : '粘貼為無格式文本',
	wordpaste : '從Word貼上',
	selectall : '全選(Ctrl+A)',
	justifyleft : '靠左對齊',
	justifycenter : '置中',
	justifyright : '靠右對齊',
	justifyfull : '兩邊對齊',
	insertorderedlist : '編號',
	insertunorderedlist : '項目符號',
	indent : '增加排縮',
	outdent : '减少排縮',
	subscript : '下標',
	superscript : '上標',
	formatblock : '段落',
	fontname : '字體',
	fontsize : '文字大小',
	forecolor : '文字顏色',
	hilitecolor : '文字背景',
	bold : '粗體(Ctrl+B)',
	italic : '斜體(Ctrl+I)',
	underline : '底線(Ctrl+U)',
	strikethrough : '删除線',
	removeformat : '删除格式',
	image : '圖片',
	multiimage : '批量圖片上載',
	flash : 'Flash',
	media : '視音頻',
	table : '表格',
	tablecell : '單元格',
	hr : '插入横線',
	emoticons : '插入表情',
	link : '超連結',
	unlink : '取消超連結',
	fullscreen : '全螢幕',
	about : '關於',
	print : '打印(Ctrl+P)',
	filemanager : '文件空間',
	code : '插入程序代碼',
	map : 'Google地圖',
	baidumap : '百度地圖',
	lineheight : '行距',
	clearhtml : '清理HTML代碼',
	pagebreak : '插入分頁符號',
	quickformat : '一鍵排版',
	insertfile : '插入文件',
	template : '插入模板',
	anchor : '錨點',
	yes : '確定',
	no : '取消',
	close : '關閉',
	editImage : '圖片屬性',
	deleteImage : '删除圖片',
	editFlash : 'Flash屬性',
	deleteFlash : '删除Flash',
	editMedia : '視音頻屬性',
	deleteMedia : '删除視音頻',
	editLink : '超連結屬性',
	deleteLink : '取消超連結',
	editAnchor : '錨點屬性',
	deleteAnchor : '删除錨點',
	tableprop : '表格屬性',
	tablecellprop : '單元格屬性',
	tableinsert : '插入表格',
	tabledelete : '删除表格',
	tablecolinsertleft : '左側插入列',
	tablecolinsertright : '右側插入列',
	tablerowinsertabove : '上方插入行',
	tablerowinsertbelow : '下方插入行',
	tablerowmerge : '向下合併單元格',
	tablecolmerge : '向右合併單元格',
	tablerowsplit : '拆分行',
	tablecolsplit : '拆分列',
	tablecoldelete : '删除列',
	tablerowdelete : '删除行',
	noColor : '無顏色',
	pleaseSelectFile : '請選擇文件。',
	invalidImg : "請輸入有效的URL地址。\n只允許jpg,gif,bmp,png格式。",
	invalidMedia : "請輸入有效的URL地址。\n只允許swf,flv,mp3,wav,wma,wmv,mid,avi,mpg,asf,rm,rmvb格式。",
	invalidWidth : "寬度必須為數字。",
	invalidHeight : "高度必須為數字。",
	invalidBorder : "邊框必須為數字。",
	invalidUrl : "請輸入有效的URL地址。",
	invalidRows : '行數為必選項，只允許輸入大於0的數字。',
	invalidCols : '列數為必選項，只允許輸入大於0的數字。',
	invalidPadding : '邊距必須為數字。',
	invalidSpacing : '間距必須為數字。',
	invalidJson : '服務器發生故障。',
	uploadSuccess : '上載成功。',
	cutError : '你的瀏覽器安全設置不允許使用剪下操作，請使用快捷鍵(Ctrl+X)來完成。',
	copyError : '你的瀏覽器安全設置不允許使用複製操作，請使用快捷鍵(Ctrl+C)來完成。',
	pasteError : '你的瀏覽器安全設置不允許使用貼上操作，請使用快捷鍵(Ctrl+V)來完成。',
	ajaxLoading : '加載中，請稍候 ...',
	uploadLoading : '上載中，請稍候 ...',
	uploadError : '上載錯誤',
	'plainpaste.comment' : '請使用快捷鍵(Ctrl+V)把内容貼到下面的方框裏。',
	'wordpaste.comment' : '請使用快捷鍵(Ctrl+V)把内容貼到下面的方框裏。',
	'code.pleaseInput' : '請輸入程序代碼。',
	'link.url' : 'URL',
	'link.linkType' : '打開類型',
	'link.newWindow' : '新窗口',
	'link.selfWindow' : '當前窗口',
	'flash.url' : 'URL',
	'flash.width' : '寬度',
	'flash.height' : '高度',
	'flash.upload' : '上載',
	'flash.viewServer' : '文件空間',
	'media.url' : 'URL',
	'media.width' : '寬度',
	'media.height' : '高度',
	'media.autostart' : '自動播放',
	'media.upload' : '上載',
	'media.viewServer' : '文件空間',
	'image.remoteImage' : '圖片網址',
	'image.localImage' : '電腦上載',
	'image.remoteUrl' : '圖片地址',
	'image.localUrl' : '上載文件',
	'image.size' : '圖片大小',
	'image.width' : '寬',
	'image.height' : '高',
	'image.resetSize' : '重新設置大小',
	'image.align' : '對齊方式',
	'image.defaultAlign' : '默認方式',
	'image.leftAlign' : '靠左對齊',
	'image.rightAlign' : '靠右對齊',
	'image.imgTitle' : '圖片說明',
	'image.upload' : '瀏覽...',
	'image.viewServer' : '圖片空間',
	'multiimage.uploadDesc' : '允許用戶同時上載<%=uploadLimit%>張圖片，單張圖片容量不超過<%=sizeLimit%>',
	'multiimage.startUpload' : '開始上載',
	'multiimage.clearAll' : '全部清除',
	'multiimage.insertAll' : '全部插入',
	'multiimage.queueLimitExceeded' : '文件數量超過限制。',
	'multiimage.fileExceedsSizeLimit' : '文件大小超過限制。',
	'multiimage.zeroByteFile' : '無法上載空白文件。',
	'multiimage.invalidFiletype' : '文件類型不正確。',
	'multiimage.unknownError' : '發生異常，無法上載。',
	'multiimage.pending' : '等待上載',
	'multiimage.uploadError' : '上載失敗',
	'filemanager.emptyFolder' : '空文件夾',
	'filemanager.moveup' : '移到上一級文件夾',
	'filemanager.viewType' : '顯示方式：',
	'filemanager.viewImage' : '縮略圖',
	'filemanager.listImage' : '詳細信息',
	'filemanager.orderType' : '排序方式：',
	'filemanager.fileName' : '名稱',
	'filemanager.fileSize' : '大小',
	'filemanager.fileType' : '類型',
	'insertfile.url' : 'URL',
	'insertfile.title' : '文件說明',
	'insertfile.upload' : '上載',
	'insertfile.viewServer' : '文件空間',
	'table.cells' : '單元格數',
	'table.rows' : '行數',
	'table.cols' : '列數',
	'table.size' : '大小',
	'table.width' : '寬度',
	'table.height' : '高度',
	'table.percent' : '%',
	'table.px' : 'px',
	'table.space' : '邊距間距',
	'table.padding' : '邊距',
	'table.spacing' : '間距',
	'table.align' : '對齊方式',
	'table.textAlign' : '水平對齊',
	'table.verticalAlign' : '垂直對齊',
	'table.alignDefault' : '默認',
	'table.alignLeft' : '靠左對齊',
	'table.alignCenter' : '置中',
	'table.alignRight' : '靠右對齊',
	'table.alignTop' : '頂部',
	'table.alignMiddle' : '中部',
	'table.alignBottom' : '底部',
	'table.alignBaseline' : '基線',
	'table.border' : '邊框',
	'table.borderWidth' : '邊框',
	'table.borderColor' : '顏色',
	'table.backgroundColor' : '背景顏色',
	'map.address' : '地址: ',
	'map.search' : '搜索',
	'baidumap.address' : '地址: ',
	'baidumap.search' : '搜索',
	'baidumap.insertDynamicMap' : '插入動態地圖',
	'anchor.name' : '錨點名稱',
	'formatblock.formatBlock' : {
		h1 : '標題 1',
		h2 : '標題 2',
		h3 : '標題 3',
		h4 : '標題 4',
		p : '正 文'
	},
	'fontname.fontName' : {
		'SimSun' : '宋體',
		'NSimSun' : '新宋體',
		'FangSong_GB2312' : '仿宋_GB2312',
		'KaiTi_GB2312' : '楷體_GB2312',
		'SimHei' : '黑體',
		'Microsoft YaHei' : '微軟雅黑',
		'Arial' : 'Arial',
		'Arial Black' : 'Arial Black',
		'Times New Roman' : 'Times New Roman',
		'Courier New' : 'Courier New',
		'Tahoma' : 'Tahoma',
		'Verdana' : 'Verdana'
	},
	'lineheight.lineHeight' : [
		{'1' : '單倍行距'},
		{'1.5' : '1.5倍行距'},
		{'2' : '2倍行距'},
		{'2.5' : '2.5倍行距'},
		{'3' : '3倍行距'}
	],
	'template.selectTemplate' : '可選模板',
	'template.replaceContent' : '替換當前内容',
	'template.fileList' : {
		'1.html' : '圖片和文字',
		'2.html' : '表格',
		'3.html' : '項目編號'
	}
}, 'zh_CN');
